# Generated by Django 3.1.6 on 2021-02-08 10:26

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('State', models.CharField(max_length=60)),
                ('District', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField(default=0)),
            ],
        ),
    ]
