# Generated by Django 3.1.6 on 2021-02-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg_franchise',
            name='Phone',
        ),
    ]
