# Generated by Django 3.1.6 on 2021-02-08 11:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0003_auto_20210208_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_franchise',
            name='Image',
            field=models.ImageField(default='Nil', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='reg_franchise',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
