# Generated by Django 3.1.6 on 2021-02-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0005_franchise_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='franchise_request',
            new_name='franchise',
        ),
    ]
