# Generated by Django 3.1.6 on 2021-02-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0007_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
