# Generated by Django 3.1.6 on 2021-02-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careapp', '0009_auto_20210211_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
